### ISSUE TITLE
Hi, Ms Teerapat Jenrungrot

### ISSUE THREAD

**Issue by GitYesm** [mjenrungrot/musescore-dataset-generator#2]
Sorry for contacting you in this way, I tried to get your email at your personal website but there was a little problem. Can you leave your email here? I would like to ask some questions about LMCodec

**Comment by GitYesm** [comment]
Sorry for contacting you in this way, I tried to get your email at your personal website but there was a little problem. Can you leave your email here? I would like to ask some questions about LMCodec

**Comment by mjenrungrot** [comment]
Hi, please contact me at tjenrung [at] cs [dot] washington [dot] edu.
